services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432" # Expõe a porta do Postgres para o seu PC
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persiste os dados do banco
    healthcheck: # Verifica se o banco de dados está pronto para conexões
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  # Serviço da Aplicação Spring
  app:
    build: . # Constrói a imagem a partir do Dockerfile no diretório atual
    container_name: chef-manager-api-app
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

# Serviço banco de dados PostgreSQL para o SonarQube
  sonar-db:
    image: postgres:16-alpine
    container_name: sonar_db
    environment:
      POSTGRES_USER: ${DB_SONAR_USER}
      POSTGRES_PASSWORD: ${DB_SONAR_PASSWORD}
      POSTGRES_DB: ${DB_SONAR_NAME}
    networks:
      - app-network
    volumes:
      - sonar-db-data:/var/lib/postgresql/data
    healthcheck: # Verifica se o banco de dados está pronto para conexões
      test: [ "CMD-SHELL", "pg_isready -U ${DB_SONAR_USER} -d ${DB_SONAR_NAME}" ]
      interval: 5s
      timeout: 5s

# Serviço do SonarQube
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      sonar-db:
        condition: service_healthy
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-db:5432/${DB_SONAR_NAME}
      - SONAR_JDBC_USERNAME=${DB_SONAR_USER}
      - SONAR_JDBC_PASSWORD=${DB_SONAR_PASSWORD}
    networks:
      - app-network
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

# Declaração dos volumes e redes
volumes:
  postgres-data:        # Volume nomeado para persistir os dados
  sonar-db-data:        # Volume nomeado para o banco de dados do SonarQube
  sonarqube_data:       # Volume para dados do SonarQube
  sonarqube_extensions: # Volume para extensões do SonarQube
  sonarqube_logs:       # Volume para logs do SonarQube

networks:
  app-network: # Rede customizada para os serviços se comunicarem

